/left_leg_servo/left_leg_servo:
  ros__parameters:
    moveit_servo:
      move_group_name: left_leg
      planning_frame: base_link
      ee_frame_name: Link_Ankle_Roll_Left
      cartesian_command_in_topic: ~/delta_twist_cmds
      joint_command_in_topic: ~/delta_joint_cmds
      command_out_topic: /left_leg_controller/joint_trajectory
      status_topic: ~/status
      joint_topic: /joint_states
      command_out_type: trajectory_msgs/JointTrajectory
      publish_period: 0.01
      is_primary_planning_scene_monitor: true
      monitored_planning_scene_topic: /monitored_planning_scene
      scale:
        linear: 0.3
        rotational: 0.5
        joint: 0.5
      incoming_command_timeout: 0.1
      num_outgoing_halt_msgs_to_publish: 4
      check_collisions: true
      check_singularity: false
      collision_check_rate: 10.0
      self_collision_proximity_threshold: 0.01
      scene_collision_proximity_threshold: 0.02
      lower_singularity_threshold: 100.0
      hard_stop_singularity_threshold: 200.0
      joint_limit_margin: 0.02
      use_smoothing: true
      smoothing_filter_plugin_name: "online_signal_smoothing::ButterworthFilterPlugin"
      publish_joint_positions: true
      publish_joint_velocities: false
      publish_joint_accelerations: false
